package com.bustracking.shared.exception;

public enum ErrorCode {
    // VALIDATION
    INVALID_INPUT,
    INVALID_EMAIL,
    INVALID_FORMAT,
    MISSING_REQUIRED_FIELD,

    // NOT FOUND
    USER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    ADMIN_NOT_FOUND,

    // BUSINESS RULES
    ADMIN_NOT_ACTIVE,
    INVALID_STATE,
    DUPLICATE_RESOURCE,
    INSUFFICIENT_PERMISSIONS,

    // EXTERNAL SERVICES
    EXTERNAL_SERVICE_ERROR,
    SERVICE_UNAVAILABLE,

    // AUTHENTICATION
    UNAUTHORIZED,
    FORBIDDEN,

    // GENERIC
    EXTERNAL_ERROR,
    INTERNAL_ERROR
}
