import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"


/**
 * Default utility function generated by shadcn that merges Tailwind CSS classes safely.
 *
 * @param clsx   - Combines class names conditionally (similar to the `classnames` library)
 * @param twMerge - Resolves Tailwind conflicts by keeping the last conflicting utility
 *
 * @example
 * // Without cn() — Tailwind conflict, unclear which px wins
 * <button className="px-4 py-2 px-6">
 *
 * // With cn() — twMerge resolves it, px-6 wins
 * <button className={cn("px-4 py-2", "px-6")}>
 */

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
